#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument

if [ "$1" ]; then
	IP_ADDRESS = "8.8.8.8"
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi
