#!/usr/bin/env bash
# The script extends previous exercise command, write a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
