#!/usr/bin/env bash
# Bash script that loops from 1 to 10:
# displays "bad luck" for the 4th loop iteration
#	"good luck" for the 8th loop iteration
# 	"Best School" for the other iterations

x=0

while ((x<10))
do
	if ((x==3))
	then
		echo "bad luck"
	elif ((x==7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
